#version: '3.8'

services:
  postgres-fire-incidents:
    image: postgres:13
    container_name: fire_incidents_db_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fire_incidents_db
    volumes:
      - ./fire_incidents_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network-fire-incidents

  pgadmin-fire-incidents:
    image: dpage/pgadmin4
    container_name: pgadmin-fire-incidents-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - pg-network-fire-incidents

    
        
networks:
  pg-network-fire-incidents:
    external: true