FROM apache/airflow:2.10.5

# Switch to root user for system-level installations
USER root

# Install Java (required by PySpark)
#RUN apt-get update && apt-get install -y openjdk-11-jdk && apt-get clean
RUN apt-get update && apt-get install -y default-jdk && apt-get clean

#
# Switch back to the airflow user
USER airflow

# Install PySpark
RUN pip install pyspark




